/************************************************************************
 ************************************************************************
    FAUST compiler
    Copyright (C) 2025 GRAME, Centre National de Creation Musicale
    ---------------------------------------------------------------------
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 ************************************************************************
 ************************************************************************/

#include "jax_code_container.hh"
#include "Text.hh"
#include "exception.hh"
#include "floats.hh"
#include "global.hh"

using namespace std;

/*
JAX backend and module description:
- The JAX backend generates several functions:
  1. `setup(self) -> None:`
  2. `_initialize_carry(self, x: jnp.ndarray, length: int):`
  3. `tick(self, params: dict, state: dict, inputs: jnp.array) -> Tuple[dict, jnp.ndarray]:`

`setup` implements a method of a flax.linen.Module. In this method, we are allowed to assign attributes
to `self`. For example, a commonly autogenerated property is a constant related to the sample-rate:
```python
self._fConst0 = np.minimum(np.float32(1.92e+05), np.maximum(np.float32(1.0), (self._fSampleRate)))
```

Other attributes are set indirectly because `setup` may call `self.add_hslider(...)`, which is implemented by
an architecture file, which almost certainly calls `self.param(...)`

`setup` is also where signals for rdtables are created. They are constants, so they shouldn't be in the "state"
which is repeatedly modified by the `tick` function.

`_initialize_carry` is where the "state"/"carry" is initialized. It cannot set anything to `self`.
This is where delay lines and signals for rwtables are created.
We also have a bias towards using numpy operations here instead of JAX numpy operations because they're faster.
The code should cast to JAX numpy late inside `_initialize_carry`.

`tick` returns a tuple of the new state and the new audio, which could have multiple channels.
It's the closest thing to a "compute" method compared to other Faust backends. Since it computes one new sample,
not a block of samples, it's similar to `-os` or `--one-sample` from command-line Faust in other backends.
  
The architecture file (`architecture/jax/minimal.py`) ties all of these functions together.

One tricky part of JAX is modifying arrays in-place:
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

Whereas C++ would look like:
`fRec1[0] = fTemp0`
in JAX we have to do:
`state["fRec1"] = state["fRec1"].at[0].set(fTemp0)`

Also, this at-and-set operation is slow, so we try to only use it inside the tick method as necessary.
This is why in all other places (like initializing waveforms and soundfiles) we use non-JAX numpy.

The JAXInitFieldsVisitor class does initialization for waveforms. We also use fUseNumpy in this
decision making. The `JAXCodeContainer` later converts the numpy arrays to jax numpy at the beginning of the `tick` method.
*/

map<string, bool> JAXInstVisitor::gFunctionSymbolTable;

dsp_factory_base* JAXCodeContainer::produceFactory()
{
    return new text_dsp_factory_aux(
        fKlassName, "", "",
        ((dynamic_cast<ostringstream*>(fOut)) ? dynamic_cast<ostringstream*>(fOut)->str() : ""),
        "");
}

JAXCodeContainer::JAXCodeContainer(const std::string& name, int numInputs, int numOutputs,
                                   std::ostream* out)
{
    // Mandatory
    initialize(numInputs, numOutputs);
    fKlassName = name;
    fOut       = out;

    // Allocate one static visitor to be shared by main module and sub containers
    if (!gGlobal->gJAXVisitor) {
        gGlobal->gJAXVisitor = new JAXInstVisitor(out, name);
    }
}

CodeContainer* JAXCodeContainer::createScalarContainer(const string& name, int sub_container_type)
{
    return new JAXScalarCodeContainer(name, 0, 1, fOut, sub_container_type);
}

CodeContainer* JAXCodeContainer::createContainer(const string& name, int numInputs, int numOutputs,
                                                 ostream* dst)
{
    CodeContainer* container;

    if (gGlobal->gOpenCLSwitch) {
        throw faustexception("ERROR : OpenCL not supported for JAX\n");
    }
    if (gGlobal->gCUDASwitch) {
        throw faustexception("ERROR : CUDA not supported for JAX\n");
    }

    if (gGlobal->gOpenMPSwitch) {
        throw faustexception("ERROR : OpenMP not supported for JAX\n");
    } else if (gGlobal->gSchedulerSwitch) {
        throw faustexception("ERROR : Scheduler not supported for JAX\n");
    } else if (gGlobal->gVectorSwitch) {
        throw faustexception("ERROR : Vector not supported for JAX\n");
    } else {
        container = new JAXScalarCodeContainer(name, numInputs, numOutputs, dst, kInt);
    }

    return container;
}

inline string flattenJSONforPython(const string& src)
{
    string dst;
    for (size_t i = 0; i < src.size(); i++) {
        switch (src[i]) {
            case '"':
                dst += "\\\"";
                break;
            case '\\':
                dst += "/";
                break;
            case '\'':
                dst += "'";
                break;
            default:
                dst += src[i];
                break;
        }
    }
    return dst;
}

void JAXCodeContainer::produceClass()
{
    int n = 0;

    // Print header
    *fOut << "\"\"\"" << endl << "Code generated with Faust version " << FAUSTVERSION << endl;
    *fOut << "Compilation options: ";
    stringstream stream;
    gGlobal->printCompilationOptions(stream);
    *fOut << stream.str();
    tab(n, *fOut);
    *fOut << "\"\"\"";
    tab(n, *fOut);

    if (gGlobal->gFloatSize == 2) {
        tab(n, *fOut);
        *fOut << "# enable double precision: "
                 "https://jax.readthedocs.io/en/latest/notebooks/"
                 "Common_Gotchas_in_JAX.html#double-64bit-precision";
        tab(n, *fOut);
        *fOut << "import jax";
        tab(n, *fOut);
        *fOut << "jax.config.update(\"jax_enable_x64\", True)";
        tab(n, *fOut);
        *fOut << "FAUSTFLOAT = jnp.float64";
        tab(n, *fOut);
        *fOut << "FAUSTINT = jnp.int64";
        tab(n, *fOut);
    } else {
        tab(n, *fOut);
        *fOut << "# enable single precision";
        tab(n, *fOut);
        *fOut << "FAUSTFLOAT = jnp.float32";
        tab(n, *fOut);
        *fOut << "FAUSTINT = jnp.int32";
        tab(n, *fOut);
    }

    // Merge sub containers. TODO: explain this.
    mergeSubContainers();
    
    // Extract pfPerm initialization values BEFORE generating methods
    // This ensures they're available when _initialize_carry is generated
    JAXInstVisitor* jaxVisitor = static_cast<JAXInstVisitor*>(gGlobal->gJAXVisitor);
    struct PfPermExtractor : public DispatchVisitor {
        JAXInstVisitor* fJaxVisitor;
        
        PfPermExtractor(JAXInstVisitor* visitor) : fJaxVisitor(visitor) {}
        
        virtual void visit(StoreVarInst* inst) {
            string varname = inst->fAddress->getName();
            if (varname.find("pfPerm") == 0) {
                fJaxVisitor->fPfPermInitValues[varname] = inst->fValue;
            }
        }
    };
    
    PfPermExtractor extractor(jaxVisitor);
    fInitInstructions->accept(&extractor);

    // Missing math function
    tab(n, *fOut);
    *fOut << "def remainder(x, y):";
    tab(n + 1, *fOut);
    *fOut << "\"\"\"C++ std::remainder implemented with jax numpy\"\"\"";
    tab(n + 1, *fOut);
    *fOut << "quo = jnp.round(x/y)";
    tab(n + 1, *fOut);
    *fOut << "return x - quo * y";
    tab(n + 1, *fOut);

    // Functions
    tab(n, *fOut);
    gGlobal->gJAXVisitor->Tab(n);

    *fOut << "class " << fKlassName << "(nn.Module):";
    tab(n + 1, *fOut);

    // Fields
    gGlobal->gJAXVisitor->Tab(n + 1);

    tab(n + 1, *fOut);
    *fOut << "sample_rate: int";
    tab(n + 1, *fOut);
    *fOut << "soundfile_dirs: list[str] = dataclasses.field(default_factory=list)";

    tab(n + 1, *fOut);
    gGlobal->gJAXVisitor->Tab(n);

    tab(n + 1, *fOut);
    produceInfoFunctions(n + 1, "", "self", false, FunTyped::kDefault, gGlobal->gJAXVisitor);

    tab(n + 1, *fOut);
    *fOut << "# fmt: off";

    tab(n + 1, *fOut);
    *fOut << "def _initialize_carry(self, x: jnp.ndarray, length: int):";
    {
        tab(n + 2, *fOut);
        *fOut << "state = {}";
        tab(n + 2, *fOut);
        
        JAXInstVisitor* jaxVisitor = static_cast<JAXInstVisitor*>(gGlobal->gJAXVisitor);
        
        // Collect all state variables by category
        std::set<std::string> scalarDelays;
        std::set<std::string> arrayDelays;
        std::set<std::string> rwTables;
        std::set<std::string> indexVars;
        std::set<std::string> iotaVars;
        std::set<std::string> pfPermVars;
        
        // First pass: categorize all state variables
        // From scalar delay tracking
        for (const auto& varName : jaxVisitor->fScalarDelayVars) {
            scalarDelays.insert(varName);
        }
        
        // Collect waveform data for dynamic table initialization
        std::map<std::string, ValueInst*> waveformData;
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                // Collect waveform data (but not index variables)
                if ((varname.find("f" + fKlassName + "Wave") == 0 || varname.find("f" + fKlassName + "SIG") == 0 ||
                     varname.find("i" + fKlassName + "Wave") == 0 || varname.find("i" + fKlassName + "SIG") == 0) && 
                    varname.find("_idx") == std::string::npos && decl->fValue) {
                    waveformData[varname] = decl->fValue;
                }
            }
        }
        
        // From struct declarations
        for (const auto& it : fDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                
                if (varname.find("IOTA") != std::string::npos) {
                    iotaVars.insert(varname);
                } else if (varname.find("pfPerm") == 0) {
                    pfPermVars.insert(varname);
                } else if (varname.find("_idx") != std::string::npos) {
                    // Catch any index variables declared in struct
                    indexVars.insert(varname);
                } else if ((varname.find("Rec") != std::string::npos || varname.find("Vec") != std::string::npos) &&
                           scalarDelays.find(varname) == scalarDelays.end()) {
                    // Only add if not already tracked as scalar delay
                    if (array_type) {
                        arrayDelays.insert(varname);
                    } else {
                        scalarDelays.insert(varname);
                    }
                } else if ((varname.find("ftbl") == 0 && varname.find("ftbl0") != 0 && array_type) ||
                           (varname.find("itbl") == 0 && varname.find("itbl0") != 0 && array_type) ||
                           (varname == "itbl0" && array_type) ||
                           (varname == "ftbl0" && array_type)) {  // Special case for itbl0 and ftbl0
                    // Catch any read-write tables (both float and integer) in struct declarations
                    rwTables.insert(varname);
                }
            }
        }
        
        // From global declarations
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                
                if ((varname.find("ftbl") == 0 && varname.find("ftbl0") != 0) ||
                    (varname.find("itbl") == 0 && varname.find("itbl0") != 0) ||
                    varname == "itbl0" ||
                    varname == "ftbl0") {  // Special case for itbl0 and ftbl0 as read-write tables
                    rwTables.insert(varname);
                } else if (varname.find("_idx") != std::string::npos) {
                    // Include all index variables, they're all mutable state
                    indexVars.insert(varname);
                } else if (varname.find("Rec") != std::string::npos || varname.find("Vec") != std::string::npos) {
                    ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                    if (array_type && arrayDelays.find(varname) == arrayDelays.end()) {
                        arrayDelays.insert(varname);
                    }
                }
            }
        }
        
        // Section 1: Initialize scalar delays
        if (!scalarDelays.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Initialize scalar delays";
            for (const auto& varName : scalarDelays) {
                tab(n + 2, *fOut);
                *fOut << "state[\"" << varName << "\"] = ";
                if (varName[0] == 'i' || varName.find("_idx") != std::string::npos) {
                    *fOut << "np.int32(0)";
                } else if (gGlobal->gFloatSize == 1) {
                    *fOut << "np.float32(0)";
                } else {
                    *fOut << "np.float64(0)";
                }
            }
        }
        
        // Section 2: Initialize array delays
        if (!arrayDelays.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Initialize array delays";
            for (const auto& it : fDeclarationInstructions->fCode) {
                if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                    string varname = decl->fAddress->getName();
                    if (arrayDelays.find(varname) != arrayDelays.end()) {
                        ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                        if (array_type) {
                            tab(n + 2, *fOut);
                            *fOut << "state[\"" << varname << "\"] = ";
                            if (varname[0] == 'i') {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                            } else if (gGlobal->gFloatSize == 1) {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                            } else {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                            }
                        }
                    }
                }
            }
            // Also check global declarations
            for (const auto& it : fGlobalDeclarationInstructions->fCode) {
                if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                    string varname = decl->fAddress->getName();
                    if (arrayDelays.find(varname) != arrayDelays.end()) {
                        ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                        if (array_type) {
                            tab(n + 2, *fOut);
                            *fOut << "state[\"" << varname << "\"] = ";
                            if (varname[0] == 'i') {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                            } else if (gGlobal->gFloatSize == 1) {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                            } else {
                                *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                            }
                        }
                    }
                }
            }
        }
        
        // Section 3: Initialize IOTA variables
        if (!iotaVars.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Initialize IOTA variables";
            for (const auto& varName : iotaVars) {
                tab(n + 2, *fOut);
                *fOut << "state[\"" << varName << "\"] = np.int32(0)";
            }
        }
        
        // Section 4: Initialize pfPerm variables
        if (!pfPermVars.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Initialize pfPerm variables";
            for (const auto& varName : pfPermVars) {
                tab(n + 2, *fOut);
                *fOut << "state[\"" << varName << "\"] = ";
                
                // Use the actual initialization value
                if (jaxVisitor->fPfPermInitValues.find(varName) != jaxVisitor->fPfPermInitValues.end()) {
                    jaxVisitor->fUseNumpy = true;  // Ensure we use numpy for initialization
                    jaxVisitor->fPfPermInitValues[varName]->accept(jaxVisitor);
                } else {
                    // Default to 0 if no initialization value found
                    if (gGlobal->gFloatSize == 1) {
                        *fOut << "np.float32(0)";
                    } else {
                        *fOut << "np.float64(0)";
                    }
                }
            }
        }
        
        // Section 5: Initialize read-write tables
        tab(n + 2, *fOut);
        *fOut << "# Initialize read-write tables";
        // Check both global and struct declarations for read-write tables
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                if (rwTables.find(varname) != rwTables.end()) {
                    ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                    if (array_type) {
                        tab(n + 2, *fOut);
                        *fOut << "state[\"" << varname << "\"] = ";
                        if (varname[0] == 'i') {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                        } else if (gGlobal->gFloatSize == 1) {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                        } else {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                        }
                    }
                }
            }
        }
        // Also check struct declarations
        for (const auto& it : fDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                if (rwTables.find(varname) != rwTables.end()) {
                    ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                    if (array_type) {
                        tab(n + 2, *fOut);
                        *fOut << "state[\"" << varname << "\"] = ";
                        if (varname[0] == 'i') {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                        } else if (gGlobal->gFloatSize == 1) {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                        } else {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                        }
                    }
                }
            }
        }
        
        // Section 6: Initialize index variables
        if (!indexVars.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Initialize index variables";
            for (const auto& varName : indexVars) {
                tab(n + 2, *fOut);
                *fOut << "state[\"" << varName << "\"] = np.int32(0)";
            }
        }
        
        // Section 7: Initialize waveform arrays (if needed for state)
        tab(n + 2, *fOut);
        *fOut << "# Initialize waveform arrays for read-write tables";
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                // Only include non-static waveform arrays that are used in state
                if (varname.find("f" + fKlassName + "Wave") == 0 && 
                    varname.find("_idx") == std::string::npos &&
                    varname.find("SIG") == std::string::npos) {
                    ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                    if (array_type) {
                        tab(n + 2, *fOut);
                        *fOut << "state[\"" << varname << "\"] = ";
                        if (varname[0] == 'i') {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                        } else if (gGlobal->gFloatSize == 1) {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                        } else {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                        }
                    }
                }
            }
        }
        
        // Section 8: Pre-compute read-write table initialization patterns (like C++ SIG classes)
        if (!rwTables.empty()) {
            tab(n + 2, *fOut);
            *fOut << "# Pre-compute table initialization patterns";
            
            // Build mapping from SIG classes to tables and waveform data
            // Pattern: <classname>SIG0 -> itbl0, <classname>SIG1 -> ftbl1, etc.
            // Also look for corresponding waveform data: f<classname>SIG0Wave0, i<classname>SIG2Wave0, etc.
            
            std::map<std::string, std::string> sigToTable;  // SIG class -> table name
            std::map<std::string, std::string> sigToWaveform;  // SIG class -> waveform data
            
            // Extract SIG number from table names and map to waveform data
            for (const auto& tableName : rwTables) {
                // Extract table index (0, 1, 2, 3, etc.) from table name
                std::string tableIndex;
                if (tableName.find("itbl") == 0) {
                    tableIndex = tableName.substr(4); // Remove "itbl" prefix
                } else if (tableName.find("ftbl") == 0) {
                    tableIndex = tableName.substr(4); // Remove "ftbl" prefix
                } else {
                    continue; // Skip unrecognized table names
                }
                
                // Look for corresponding waveform data for this SIG class
                std::string sigWaveformName;
                for (const auto& kv : waveformData) {
                    const std::string& waveName = kv.first;
                    // Check for patterns like: f<classname>SIG0Wave0, i<classname>SIG2Wave0, etc.
                    if ((waveName.find("f" + fKlassName + "SIG" + tableIndex + "Wave") == 0) ||
                        (waveName.find("i" + fKlassName + "SIG" + tableIndex + "Wave") == 0)) {
                        sigWaveformName = waveName;
                        break;
                    }
                }
                
                if (!sigWaveformName.empty()) {
                    // Found waveform data - generate cycling pattern initialization
                    tab(n + 2, *fOut);
                    *fOut << "# Fill " << tableName << " with cycling waveform pattern from " << sigWaveformName;
                    tab(n + 2, *fOut);
                    *fOut << "waveform_pattern = np.array(self._" << sigWaveformName;
                    if (tableName.find("itbl") == 0) {
                        *fOut << ", dtype=np.int32)";
                    } else if (gGlobal->gFloatSize == 1) {
                        *fOut << ", dtype=np.float32)";
                    } else {
                        *fOut << ", dtype=np.float64)";
                    }
                    tab(n + 2, *fOut);
                    *fOut << "for i in range(state[\"" << tableName << "\"].shape[0]):";
                    tab(n + 3, *fOut);
                    *fOut << "state[\"" << tableName << "\"][i] = waveform_pattern[i % len(waveform_pattern)]";
                } else {
                    // No waveform data found - check for special patterns based on table index
                    if (tableIndex == "0" && tableName.find("itbl") == 0) {
                        // itbl0 typically uses incrementing integers (SIG0 pattern)
                        tab(n + 2, *fOut);
                        *fOut << "# Fill " << tableName << " with incrementing integers (SIG0 pattern)";
                        tab(n + 2, *fOut);
                        *fOut << "for i in range(state[\"" << tableName << "\"].shape[0]):";
                        tab(n + 3, *fOut);
                        *fOut << "state[\"" << tableName << "\"][i] = np.int32(i + 1)";
                    } else if (tableIndex == "1" && tableName.find("ftbl") == 0) {
                        // ftbl1 typically uses incrementing floats by 0.1 (SIG1 pattern)
                        tab(n + 2, *fOut);
                        *fOut << "# Fill " << tableName << " with incrementing floats by 0.1 (SIG1 pattern)";
                        tab(n + 2, *fOut);
                        *fOut << "for i in range(state[\"" << tableName << "\"].shape[0]):";
                        tab(n + 3, *fOut);
                        if (gGlobal->gFloatSize == 1) {
                            *fOut << "state[\"" << tableName << "\"][i] = np.float32((i + 1) * 0.1)";
                        } else {
                            *fOut << "state[\"" << tableName << "\"][i] = np.float64((i + 1) * 0.1)";
                        }
                    } else {
                        // Unknown pattern - leave as zeros but add warning comment
                        tab(n + 2, *fOut);
                        *fOut << "# WARNING: Unknown initialization pattern for " << tableName;
                        tab(n + 2, *fOut);
                        *fOut << "# Table will remain initialized to zeros";
                    }
                }
            }
        }
        
        // Section 9: Process inline subcontainers for read-write table initialization
        if (!rwTables.empty() && fStaticInitInstructions->fCode.size() > 0) {
            tab(n + 2, *fOut);
            *fOut << "# Process inline subcontainers for read-write table initialization";
            
            // We need to process the same inline subcontainer code, but this time
            // we're in _initialize_carry context so read-write tables are accessible
            
            // Extract and declare local variables needed for inline subcontainers
            struct LocalVarExtractor : public DispatchVisitor {
                std::set<std::string> fLocalVars;
                
                virtual void visit(StoreVarInst* inst) {
                    string varname = inst->fAddress->getName();
                    // Capture all variables that look like temporary/local variables
                    // but exclude table names (ftbl* and itbl*)
                    if (varname.find("ftbl") != 0 && varname.find("itbl") != 0 &&  // Exclude table names
                        (varname.find("Vec") != std::string::npos || 
                         varname.find("Rec") != std::string::npos ||
                         varname.find("_idx") != std::string::npos ||
                         varname[0] == 'i')) {  // Only include integer vars starting with 'i'
                        fLocalVars.insert(varname);
                    }
                }
            };
            
            LocalVarExtractor extractor;
            inlineSubcontainersFunCalls(fStaticInitInstructions)->accept(&extractor);
            
            // Add common inline subcontainer variables that might not be detected
            extractor.fLocalVars.insert("iRec16");  // Common in table filling code
            
            // Declare local variables (use a set to avoid duplicates)
            std::set<std::string> declaredVars;
            for (const auto& varname : extractor.fLocalVars) {
                if (declaredVars.find(varname) == declaredVars.end()) {
                    tab(n + 2, *fOut);
                    *fOut << varname << " = ";
                    if (varname[0] == 'i' || varname.find("_idx") != std::string::npos) {
                        *fOut << "np.int32(0)";
                    } else if (gGlobal->gFloatSize == 1) {
                        *fOut << "np.float32(0)";
                    } else {
                        *fOut << "np.float64(0)";
                    }
                    tab(n + 2, *fOut);
                    declaredVars.insert(varname);
                }
            }
            
            // Process inline subcontainer code
            // This time we're not in static init, so read-write tables will be accessed from state
            gGlobal->gJAXVisitor->Tab(n + 2);
            jaxVisitor->fInStaticInit = false;
            jaxVisitor->fInSetup = false;
            jaxVisitor->fInInlineSubcontainer = true;
            // Pass the set of local variables to the visitor
            for (const auto& varname : extractor.fLocalVars) {
                jaxVisitor->fInlineSubcontainerLocals.insert(varname);
            }
            inlineSubcontainersFunCalls(fStaticInitInstructions)->accept(gGlobal->gJAXVisitor);
            jaxVisitor->fInInlineSubcontainer = false;
            jaxVisitor->fInlineSubcontainerLocals.clear();
        }
        
        // If we skipped all loops and there's no other code, add a pass statement
        if (rwTables.empty() && fStaticInitInstructions->fCode.size() > 0) {
            tab(n + 2, *fOut);
            *fOut << "pass  # No read-write tables to initialize";
        }
        
        tab(n + 2, *fOut);
        *fOut << "return state";
        tab(n + 1, *fOut);
    }
    back(1, *fOut);

    // todo: enable this. It's disabled for now because it makes generated files very long, which is bad for LLM usage.
    // JSON generation
    // tab(n + 1, *fOut);
    // *fOut << "@property";
    // tab(n + 1, *fOut);
    // *fOut << "def json_metadata(self):";
    // {
    //     string json;
    //     if (gGlobal->gFloatSize == 1) {
    //         json = generateJSON<float>();
    //     } else {
    //         json = generateJSON<double>();
    //     }
    //     tab(n + 2, *fOut);
    //     *fOut << "json_str = \"\"\"" << flattenJSONforPython(json) << "\"\"\"";
    //     tab(n + 2, *fOut);
    //     *fOut << "return json.loads(json_str)";
    //     tab(n + 1, *fOut);
    // }

    // Setup method - handles only immutable instance attributes and constants
    tab(n + 1, *fOut);
    *fOut << "def setup(self):";
    {
        JAXInstVisitor* jaxVisitor = static_cast<JAXInstVisitor*>(gGlobal->gJAXVisitor);
        jaxVisitor->fUseNumpy = true;
        jaxVisitor->fInSetup = true;
        
        // Section 1: Initialize constants
        // Note: sample_rate is accessed directly as self.sample_rate, no need to store it
        
        // Section 2: Collect all static tables and waveform data
        std::map<std::string, ValueInst*> waveformData;
        std::set<std::string> staticTables;
        
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                
                // Collect static tables (ftbl0* and itbl0*<classname>SIG*)
                if (varname.find("ftbl0") == 0 || 
                    (varname.find("itbl0") == 0 && varname.find(fKlassName + "SIG") != std::string::npos)) {
                    staticTables.insert(varname);
                }
                // Collect waveform data (but not index variables)
                else if ((varname.find("f" + fKlassName + "Wave") == 0 || varname.find("f" + fKlassName + "SIG") == 0 ||
                          varname.find("i" + fKlassName + "Wave") == 0 || varname.find("i" + fKlassName + "SIG") == 0) && 
                         varname.find("_idx") == std::string::npos && decl->fValue) {
                    waveformData[varname] = decl->fValue;
                }
            }
        }
        
        // Section 3: Initialize static tables as instance attributes
        tab(n + 2, *fOut);
        *fOut << "# Initialize static tables";
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                if (varname.find("ftbl0") == 0 || 
                    (varname.find("itbl0") == 0 && varname.find(fKlassName + "SIG") != std::string::npos)) {
                    tab(n + 2, *fOut);
                    // Use numpy for initialization, will convert to JAX later
                    *fOut << varname << " = ";
                    ArrayTyped* array_type = dynamic_cast<ArrayTyped*>(decl->fType);
                    if (array_type) {
                        if (varname.find("itbl0") == 0) {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.int32)";
                        } else if (gGlobal->gFloatSize == 1) {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float32)";
                        } else {
                            *fOut << "np.zeros((" << array_type->fSize << ",), dtype=np.float64)";
                        }
                    }
                    jaxVisitor->fConstantVars.insert(varname);
                }
            }
        }
        
        // Section 4: Initialize waveform data
        tab(n + 2, *fOut);
        *fOut << "# Initialize waveform data";
        // Keep using numpy for waveform data during setup
        for (const auto& kv : waveformData) {
            tab(n + 2, *fOut);
            *fOut << "self._" << kv.first << " = ";
            kv.second->accept(jaxVisitor);
            jaxVisitor->fConstantVars.insert(kv.first);
        }
        
        // Section 5: Process inline subcontainers (for filling static tables)
        if (fStaticInitInstructions->fCode.size() > 0) {
            tab(n + 2, *fOut);
            *fOut << "# Process inline subcontainers for static table initialization";
            
            // Extract and declare local variables needed for inline subcontainers
            struct LocalVarExtractor : public DispatchVisitor {
                std::set<std::string> fLocalVars;
                
                virtual void visit(StoreVarInst* inst) {
                    string varname = inst->fAddress->getName();
                    // Capture all variables that look like temporary/local variables
                    // but exclude table names (ftbl* and itbl*)
                    if (varname.find("ftbl") != 0 && varname.find("itbl") != 0 &&  // Exclude table names
                        (varname.find("Vec") != std::string::npos || 
                         varname.find("Rec") != std::string::npos ||
                         varname.find("_idx") != std::string::npos ||
                         varname[0] == 'i')) {  // Only include integer vars starting with 'i'
                        fLocalVars.insert(varname);
                    }
                }
            };
            
            LocalVarExtractor extractor;
            inlineSubcontainersFunCalls(fStaticInitInstructions)->accept(&extractor);
            
            // Declare local variables
            if (!extractor.fLocalVars.empty()) {
                tab(n + 2, *fOut);
            }
            for (const auto& varname : extractor.fLocalVars) {
                *fOut << varname << " = ";
                if (varname[0] == 'i' || varname.find("_idx") != std::string::npos) {
                    *fOut << "np.int32(0)";
                } else if (gGlobal->gFloatSize == 1) {
                    *fOut << "np.float32(0)";
                } else {
                    *fOut << "np.float64(0)";
                }
                tab(n + 2, *fOut);
            }
            
            // Process inline subcontainer code
            gGlobal->gJAXVisitor->Tab(n + 2);
            jaxVisitor->fInStaticInit = true;
            inlineSubcontainersFunCalls(fStaticInitInstructions)->accept(gGlobal->gJAXVisitor);
            jaxVisitor->fInStaticInit = false;
        }
        
        // Section 5.5: Convert static tables to JAX arrays and freeze them
        // Static tables need to be JAX arrays for indexing within JIT-compiled code,
        // but they should be marked as static (non-trainable) to avoid issues
        tab(n + 2, *fOut);
        *fOut << "# Convert static tables and waveform data to JAX arrays";
        for (const auto& it : fGlobalDeclarationInstructions->fCode) {
            if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
                string varname = decl->fAddress->getName();
                if (varname.find("ftbl0") == 0 || 
                    (varname.find("itbl0") == 0 && varname.find(fKlassName + "SIG") != std::string::npos)) {
                    tab(n + 2, *fOut);
                    // Convert to JAX array
                    *fOut << "self._" << varname << " = jnp.array(" << varname << ")";
                }
            }
        }
        
        // Section 6: Initialize UI parameters
        tab(n + 2, *fOut);
        *fOut << "# Initialize UI parameters";
        tab(n + 2, *fOut);
        *fOut << "unnorm_funcs = {}";
        tab(n + 2, *fOut);
        *fOut << "ui_path = []";
        tab(n + 2, *fOut);
        gGlobal->gJAXVisitor->Tab(n + 2);
        generateUserInterface(gGlobal->gJAXVisitor);
        tab(n + 2, *fOut);
        *fOut << "self._unnorm_funcs = unnorm_funcs";
        
        // Section 7: Initialize constants from init instructions
        tab(n + 2, *fOut);
        *fOut << "# Initialize other constants";
        
        struct ConstantInitExtractor : public DispatchVisitor {
            std::ostream* fOut;
            int fTab;
            JAXInstVisitor* fJaxVisitor;
            
            ConstantInitExtractor(std::ostream* out, int tab, JAXInstVisitor* visitor) 
                : fOut(out), fTab(tab), fJaxVisitor(visitor) {}
                
            virtual void visit(StoreVarInst* inst) {
                string varname = inst->fAddress->getName();
                if (varname.find("Const") != std::string::npos) {
                    fJaxVisitor->fConstantVars.insert(varname);
                    tab(fTab, *fOut);
                    inst->accept(fJaxVisitor);
                } else if (varname.find("pfPerm") == 0) {
                    // Store pfPerm initialization values for _initialize_carry
                    fJaxVisitor->fPfPermInitValues[varname] = inst->fValue;
                }
            }
        };
        
        ConstantInitExtractor extractor(fOut, n + 2, jaxVisitor);
        fInitInstructions->accept(&extractor);
        
        // Reset context flags
        jaxVisitor->fInSetup = false;
    }

    // Compute
    jaxVisitor->fInTick = true;
    generateCompute(n + 1);
    jaxVisitor->fInTick = false;
}

void JAXCodeContainer::generateCompute(int n)
{
    tab(n, *fOut);
    *fOut << "def tick(self, params: dict, state: dict, inputs: jnp.array) -> Tuple[dict, jnp.ndarray]:";
    tab(n + 1, *fOut);

    tab(n + 1, *fOut);
    gGlobal->gJAXVisitor->Tab(n + 1);

    // todo: this section below repeats code elsewhere
    // Collect waveform data for dynamic table initialization
    std::map<std::string, ValueInst*> waveformData;
    for (const auto& it : fGlobalDeclarationInstructions->fCode) {
        if (DeclareVarInst* decl = dynamic_cast<DeclareVarInst*>(it)) {
            string varname = decl->fAddress->getName();
            // Collect waveform data (but not index variables)
            if ((varname.find("f" + fKlassName + "Wave") == 0 || varname.find("f" + fKlassName + "SIG") == 0 ||
                    varname.find("i" + fKlassName + "Wave") == 0 || varname.find("i" + fKlassName + "SIG") == 0) && 
                varname.find("_idx") == std::string::npos && decl->fValue) {
                waveformData[varname] = decl->fValue;
            }
        }
    }

    if (waveformData.size() > 0) {
        *fOut << "# Convert waveform data to JAX arrays";
        // Convert waveform data to JAX arrays
        for (const auto& kv : waveformData) {
            tab(n + 1, *fOut);
            *fOut << kv.first << " = jnp.array(self._" << kv.first << ")";
        }
        tab(n + 1, *fOut);
        tab(n + 1, *fOut);
    }

    // Generates local variables declaration and setup
    gGlobal->gJAXVisitor->fUseNumpy = false;
    generateComputeBlock(gGlobal->gJAXVisitor);

    auto loop = fCurLoop->generateOneSample();
    loop->accept(gGlobal->gJAXVisitor);

    generatePostComputeBlock(gGlobal->gJAXVisitor);
    gGlobal->gJAXVisitor->fUseNumpy = true;

    tab(n, *fOut);
    *fOut << "# fmt: on";
}

void JAXCodeContainer::generateSR()
{
    // In JAX, we don't need to store sample_rate in state
    // We can access it directly as self.sample_rate
    // So we do nothing here
}

void JAXCodeContainer::produceInfoFunctions(int tabs, const string& classname, const string& obj,
                                           bool ismethod, FunTyped::FunAttribute funtype,
                                           TextInstVisitor* producer, const string& in_fun,
                                           const string& out_fun)
{
    // Generate as properties instead of methods for JAX/Flax
    *fOut << "@property";
    tab(tabs, *fOut);
    *fOut << "def num_inputs(self):";
    tab(tabs + 1, *fOut);
    *fOut << "return " << fNumInputs;
    tab(tabs, *fOut);
    
    tab(tabs, *fOut);
    *fOut << "@property";
    tab(tabs, *fOut);
    *fOut << "def num_outputs(self):";
    tab(tabs + 1, *fOut);
    *fOut << "return " << fNumOutputs;
    tab(tabs, *fOut);
}

// Scalar
JAXScalarCodeContainer::JAXScalarCodeContainer(const string& name, int numInputs, int numOutputs,
                                               std::ostream* out, int sub_container_type)
    : JAXCodeContainer(name, numInputs, numOutputs, out)
{
    fSubContainerType = sub_container_type;
}
