name: libfaust

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build-ubuntu:
    strategy:
      matrix:
        include:
          - name: ubuntu-x86_64
            theContainer: docker://quay.io/pypa/manylinux2014_x86_64
            os: ubuntu-latest
            cmake-options: >-
              -DCMAKE_BUILD_TYPE=Release
              -DCMAKE_VERBOSE_MAKEFILE=ON
            llvm-options: >-
              -DLLVM_TARGETS_TO_BUILD="X86"
              -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-linux-gnu"

    runs-on: ubuntu-latest
    container:
      image: ${{matrix.theContainer}}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Checkout ncurses
      uses: actions/checkout@v3
      with:
        repository: mirror/ncurses
        path: ncurses

    - name: ncurses install
      run: |
        yum install zip -y
        cd ncurses
        ./configure --prefix=/usr/local/ncurses/6_3 --with-shared --with-pkg-config-libdir=/usr/local/ncurses/6_3/lib/pkgconfig --enable-pc-files
        make
        make install

    # - name: Restore libsndfile
    #   id: cache-libsndfile-restore
    #   uses: actions/cache/restore@v3
    #   with:
    #     path: libsndfile
    #     key: cache-libsndfile-${{ matrix.name }}

    - name: Clone libsndfile
      # if: steps.cache-libsndfile-restore.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: libsndfile/libsndfile
        path: libsndfile

    - name: Build libsndfile
      # if: steps.cache-libsndfile-restore.outputs.cache-hit != 'true'
      run: |
        cd libsndfile
        mkdir CMakeBuild && cd CMakeBuild
        cmake .. -G "Unix Makefiles" ${{matrix.cmake-options}} -DENABLE_EXTERNAL_LIBS=off -DBUILD_EXAMPLES=OFF
        cmake --build . --config Release

    # - name: Cache libsndfile output
    #   id: cache-libsndfile-save
    #   uses: actions/cache/save@v3
    #   with:
    #     path: libsndfile
    #     key: ${{ steps.cache-libsndfile-restore.outputs.cache-primary-key }}

    - name: Restore LLVM
      id: cache-llvm-restore
      uses: actions/cache/restore@v3
      with:
        path: llvm-project
        key: cache-llvm-${{ matrix.name }}

    - name: Clone LLVM
      if: steps.cache-llvm-restore.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
        repository: llvm/llvm-project
        path: llvm-project
        ref: f28c006a5895fc0e329fe15fead81e37457cb1d1

    - name: Build LLVM
      if: steps.cache-llvm-restore.outputs.cache-hit != 'true'
      run: |
        cd llvm-project/llvm
        cmake -Bbuild -DCMAKE_INSTALL_PREFIX="./llvm" ${{matrix.cmake-options}} ${{matrix.llvm-options}} -DLLVM_ENABLE_ZLIB=off -DLLVM_OPTIMIZED_TABLEGEN=ON
        cmake --build build --config Release

    - name: Cache LLVM output
      id: cache-llvm-save
      uses: actions/cache/save@v3
      with:
        path: llvm-project
        key: ${{ steps.cache-llvm-restore.outputs.cache-primary-key }}

    - name: Build libfaust
      run: |
        export CURSES_LIBRARY="/usr/local/ncurses/6_3/lib"
        cd build
        cmake  -C ./backends/all.cmake . -Bbuild ${{matrix.cmake-options}} -DINCLUDE_DYNAMIC=ON -DINCLUDE_LLVM=ON -DUSE_LLVM_CONFIG=off -DINCLUDE_SNDFILE=ON -DINCLUDE_CURSES=ON -DCMAKE_PREFIX_PATH="$PWD/../llvm-project/llvm/build/lib/cmake/llvm;$PWD/../libsndfile/cmake" -DCURSES_LIBRARY=$CURSES_LIBRARY
        cmake --build build --config Release
   
    - name: Make distribution
      run: |
        mkdir libfaust_dist
        cp -v -r build/lib libfaust_dist
        zip -r libfaust-${{ matrix.name }}.zip libfaust_dist
   
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact-${{ matrix.name }}
        path: libfaust-${{ matrix.name }}.zip